// Loader + reshaping for public/power_money.json — Austin Energy fuel spending by year.
// Generated by scripts/eia_fuel_costs.py from EIA Form 923 (facility-fuel) heat input and
// EIA Texas electric-utility fuel cost per MMBtu.

export type FuelKey =
  | "coal"
  | "gas"
  | "oil"
  | "nuclear"
  | "wind"
  | "solar"
  | "hydro"
  | "biomass"
  | "other";

export interface FuelYearEntry {
  mwh: number;
  fuelUsd: number;
  contractedUsd: number;
  totalUsd: number;
  varOmUsd: number;
  fixedOmUsd: number;
  capitalUsd: number;
  nonFuelUsd: number;
  totalWithNonFuelUsd: number;
  usdPerMwh: number | null;
  usdPerMwhWithNonFuel: number | null;
  /** true when the dollars come from EIA-reported fuel costs, false when from a documented assumption */
  measured: boolean;
}

export interface PowerMoneyYear {
  year: number;
  fuels: Partial<Record<FuelKey, FuelYearEntry>>;
  totalUsd: number;
  nonFuelUsd: number;
  systemCostsUsd: number | null;
  totalWithNonFuelUsd: number;
  fullSystemUsd: number | null;
  totalMwh: number;
  resCustomers: number;
  perHouseholdUsd: number;
  perHouseholdWithNonFuelUsd: number;
  perHouseholdFullUsd: number | null;
  partial: boolean;
}

export interface PowerMoneyData {
  generated: string;
  lastPeriod: string | null;
  years: PowerMoneyYear[];
  assumptions: {
    contractedUsdPerMwh: Record<string, [number, number][]>;
    residentialShareOfSales: number;
    aeResidentialCustomers: Record<string, number>;
    aePct: Record<string, number>;
    nonFuel: {
      rates: Record<string, { varOmUsdPerMwh: number; fixedOmUsdPerKwYr: number; capitalUsdPerKwYr: number }>;
      ownedCapacityMw: Record<string, number>;
      source: string;
    };
    systemCosts: {
      usdByYear: Record<string, number>;
      startYear: number;
      source: string;
    };
  };
}

// Palette matches the fuel colors used in src/components/No2Section.tsx.
export const FUEL_META: Record<FuelKey, { label: string; color: string }> = {
  coal: { label: "Coal", color: "#991b1b" },
  gas: { label: "Natural gas", color: "#d97706" },
  oil: { label: "Fuel oil", color: "#78350f" },
  nuclear: { label: "Nuclear", color: "#7c3aed" },
  wind: { label: "Wind", color: "#0ea5e9" },
  solar: { label: "Solar", color: "#eab308" },
  hydro: { label: "Hydro", color: "#0891b2" },
  biomass: { label: "Biomass", color: "#15803d" },
  other: { label: "Other", color: "#64748b" },
};

export const FUEL_ORDER: FuelKey[] = [
  "coal",
  "gas",
  "oil",
  "nuclear",
  "biomass",
  "hydro",
  "wind",
  "solar",
];

export async function loadPowerMoney(): Promise<PowerMoneyData> {
  const res = await fetch("/power_money.json");
  if (!res.ok) throw new Error(`Failed to load fuel spending data (${res.status})`);
  return (await res.json()) as PowerMoneyData;
}

export type Basis = "total" | "household";

/**
 * Which cost layers are included.
 *  fuel    — fuel purchases + contracted energy price only
 *  plant   — plus per-fuel variable O&M, fixed O&M and capital / debt service
 *  system  — plus system costs that cannot be attributed to a fuel (T&D, congestion, admin)
 */
export type CostLayer = "fuel" | "plant" | "system";

export const LAYER_LABEL: Record<CostLayer, string> = {
  fuel: "Fuel only",
  plant: "Fuel + plant costs",
  system: "Full system cost",
};

/** Non-fuel-specific system cost bucket, rendered as its own stacked segment. */
export const SYSTEM_KEY = "systemCosts";
export const SYSTEM_META = { label: "System costs (not fuel-specific)", color: "#94a3b8" };

const fuelDollars = (f: FuelYearEntry, layer: CostLayer) =>
  layer === "fuel" ? f.totalUsd : f.totalWithNonFuelUsd;

/** One row per year with a numeric column per fuel, ready for a stacked Recharts series. */
export function toChartRows(data: PowerMoneyData, basis: Basis, layer: CostLayer = "fuel") {
  return data.years.map((y) => {
    const divisor =
      basis === "household" ? y.resCustomers / data.assumptions.residentialShareOfSales : 1;
    const digits = basis === "household" ? 2 : 0;
    const systemUsd = layer === "system" ? y.systemCostsUsd ?? 0 : 0;
    const fuelsTotal = FUEL_ORDER.reduce((sum, k) => {
      const f = y.fuels[k];
      return sum + (f ? fuelDollars(f, layer) : 0);
    }, 0);
    const row: Record<string, number | boolean | string> = {
      year: y.year,
      partial: y.partial,
      label: y.partial ? `${y.year}*` : String(y.year),
      total: +((fuelsTotal + systemUsd) / divisor).toFixed(digits),
      systemMissing: layer === "system" && y.systemCostsUsd === null,
    };
    for (const key of FUEL_ORDER) {
      const f = y.fuels[key];
      row[key] = f ? +(fuelDollars(f, layer) / divisor).toFixed(digits) : 0;
    }
    row[SYSTEM_KEY] = +(systemUsd / divisor).toFixed(digits);
    return row;
  });
}

/** Effective $/MWh per fuel per year, for the cost-trend chart. */
export function toRateRows(data: PowerMoneyData, layer: CostLayer = "fuel") {
  return data.years.map((y) => {
    const row: Record<string, number | null | string> = { year: y.year, label: String(y.year) };
    for (const key of FUEL_ORDER) {
      const f = y.fuels[key];
      row[key] = f && f.mwh > 0 ? (layer === "fuel" ? f.usdPerMwh : f.usdPerMwhWithNonFuel) : null;
    }
    return row;
  });
}

/** Total spend for a year at a given cost layer. */
export const yearTotal = (y: PowerMoneyYear, layer: CostLayer) =>
  layer === "fuel"
    ? y.totalUsd
    : layer === "plant"
      ? y.totalWithNonFuelUsd
      : y.fullSystemUsd ?? y.totalWithNonFuelUsd;

/** Per-household spend for a year at a given cost layer. */
export const yearPerHousehold = (y: PowerMoneyYear, layer: CostLayer) =>
  layer === "fuel"
    ? y.perHouseholdUsd
    : layer === "plant"
      ? y.perHouseholdWithNonFuelUsd
      : y.perHouseholdFullUsd ?? y.perHouseholdWithNonFuelUsd;

export const fuelsPresent = (data: PowerMoneyData): FuelKey[] =>
  FUEL_ORDER.filter((k) => data.years.some((y) => (y.fuels[k]?.totalUsd ?? 0) > 0));

export const usd = (n: number, digits = 0) =>
  `$${n.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits })}`;

export const usdCompact = (n: number) => {
  if (Math.abs(n) >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (Math.abs(n) >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (Math.abs(n) >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return usd(n);
};

export interface ComparisonRow {
  key: FuelKey | "localSolar";
  label: string;
  color: string;
  /** fuel purchases or contracted energy price, $/MWh */
  fuelRate: number;
  /** estimated plant O&M + capital / debt service, $/MWh (0 for PPA resources) */
  nonFuelRate: number;
  /** system delivery costs (T&D, congestion, ancillary, admin) spread evenly per MWh */
  systemRate: number;
  /** fuel + plant costs only */
  allInRate: number;
  /** fuel + plant + system delivery costs */
  deliveredRate: number;
  mwh: number;
  /** share of that year's total generation, 0-1 */
  share: number;
  /** true when the fuel dollars come from reported EIA fuel costs */
  measured: boolean;
  /** true when the energy price is a documented contract assumption */
  contracted: boolean;
}


/**
 * One row per source for a single year, delivered $/MWh, cheapest first.
 * System costs are spread evenly across every MWh generated — they are not
 * attributable to a source, so every bar carries the same system segment.
 */
export function toComparisonRows(data: PowerMoneyData, year: number): ComparisonRow[] {
  const y = data.years.find((r) => r.year === year);
  if (!y) return [];
  const systemRate =
    y.systemCostsUsd !== null && y.totalMwh > 0 ? +(y.systemCostsUsd / y.totalMwh).toFixed(2) : 0;
  const rows: ComparisonRow[] = [];
  for (const key of FUEL_ORDER) {
    const f = y.fuels[key];
    if (!f || f.mwh <= 0) continue;
    const fuelRate = f.totalUsd / f.mwh;
    const nonFuelRate = f.nonFuelUsd / f.mwh;
    rows.push({
      key,
      label: FUEL_META[key].label,
      color: FUEL_META[key].color,
      fuelRate: +fuelRate.toFixed(2),
      nonFuelRate: +nonFuelRate.toFixed(2),
      systemRate,
      allInRate: +(fuelRate + nonFuelRate).toFixed(2),
      deliveredRate: +(fuelRate + nonFuelRate + systemRate).toFixed(2),
      mwh: f.mwh,
      share: y.totalMwh > 0 ? f.mwh / y.totalMwh : 0,
      measured: f.measured,
      contracted: f.contractedUsd > 0,
    });
  }
  return rows.sort((a, b) => a.deliveredRate - b.deliveredRate);
}

