// Loader + reshaping for public/power_money.json — Austin Energy fuel spending by year.
// Generated by scripts/eia_fuel_costs.py from EIA Form 923 (facility-fuel) heat input and
// EIA Texas electric-utility fuel cost per MMBtu.

export type FuelKey =
  | "coal"
  | "gas"
  | "oil"
  | "nuclear"
  | "wind"
  | "solar"
  | "hydro"
  | "biomass"
  | "other";

export interface FuelYearEntry {
  mwh: number;
  fuelUsd: number;
  contractedUsd: number;
  totalUsd: number;
  usdPerMwh: number | null;
  /** true when the dollars come from EIA-reported fuel costs, false when from a documented assumption */
  measured: boolean;
}

export interface PowerMoneyYear {
  year: number;
  fuels: Partial<Record<FuelKey, FuelYearEntry>>;
  totalUsd: number;
  totalMwh: number;
  resCustomers: number;
  perHouseholdUsd: number;
  partial: boolean;
}

export interface PowerMoneyData {
  generated: string;
  lastPeriod: string | null;
  years: PowerMoneyYear[];
  assumptions: {
    contractedUsdPerMwh: Record<string, [number, number][]>;
    residentialShareOfSales: number;
    aeResidentialCustomers: Record<string, number>;
    aePct: Record<string, number>;
  };
}

// Palette matches the fuel colors used in src/components/No2Section.tsx.
export const FUEL_META: Record<FuelKey, { label: string; color: string }> = {
  coal: { label: "Coal", color: "#991b1b" },
  gas: { label: "Natural gas", color: "#d97706" },
  oil: { label: "Fuel oil", color: "#78350f" },
  nuclear: { label: "Nuclear", color: "#7c3aed" },
  wind: { label: "Wind", color: "#0ea5e9" },
  solar: { label: "Solar", color: "#eab308" },
  hydro: { label: "Hydro", color: "#0891b2" },
  biomass: { label: "Biomass", color: "#15803d" },
  other: { label: "Other", color: "#64748b" },
};

export const FUEL_ORDER: FuelKey[] = [
  "coal",
  "gas",
  "oil",
  "nuclear",
  "biomass",
  "hydro",
  "wind",
  "solar",
];

export async function loadPowerMoney(): Promise<PowerMoneyData> {
  const res = await fetch("/power_money.json");
  if (!res.ok) throw new Error(`Failed to load fuel spending data (${res.status})`);
  return (await res.json()) as PowerMoneyData;
}

export type Basis = "total" | "household";

/** One row per year with a numeric column per fuel, ready for a stacked Recharts series. */
export function toChartRows(data: PowerMoneyData, basis: Basis) {
  return data.years.map((y) => {
    const divisor = basis === "household" ? y.resCustomers / data.assumptions.residentialShareOfSales : 1;
    const row: Record<string, number | boolean | string> = {
      year: y.year,
      partial: y.partial,
      label: y.partial ? `${y.year}*` : String(y.year),
      total: basis === "household" ? y.perHouseholdUsd : y.totalUsd,
    };
    for (const key of FUEL_ORDER) {
      const f = y.fuels[key];
      row[key] = f ? +(f.totalUsd / divisor).toFixed(basis === "household" ? 2 : 0) : 0;
    }
    return row;
  });
}

/** Effective $/MWh per fuel per year, for the cost-trend chart. */
export function toRateRows(data: PowerMoneyData) {
  return data.years.map((y) => {
    const row: Record<string, number | null | string> = { year: y.year, label: String(y.year) };
    for (const key of FUEL_ORDER) {
      const f = y.fuels[key];
      row[key] = f && f.mwh > 0 ? f.usdPerMwh : null;
    }
    return row;
  });
}

export const fuelsPresent = (data: PowerMoneyData): FuelKey[] =>
  FUEL_ORDER.filter((k) => data.years.some((y) => (y.fuels[k]?.totalUsd ?? 0) > 0));

export const usd = (n: number, digits = 0) =>
  `$${n.toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits })}`;

export const usdCompact = (n: number) => {
  if (Math.abs(n) >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (Math.abs(n) >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (Math.abs(n) >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return usd(n);
};
