import { useEffect, useMemo, useState } from "react";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import PageHeader from "@/components/PageHeader";
import { useSeo } from "@/hooks/use-seo";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import MultiSelectDropdown from "@/components/explore/MultiSelectDropdown";

/**
 * Data comes from public/data/atb.json, generated by scripts/atb_extract.py from the NREL ATB
 * workbook. New technologies in a newer workbook appear automatically after re-running the script;
 * friendly names live in TECH_LABELS below (or techLabels in the JSON).
 */
const TECH_LABELS: Record<string, string> = {
  UtilityPV: "Utility solar",
  CommPV: "Commercial rooftop solar",
  ResPV: "Residential rooftop solar",
  LandbasedWind: "Land-based wind",
  OffShoreWind: "Offshore wind",
  DistributedWind: "Distributed wind",
  CSP: "Concentrating solar",
  NaturalGas_FE: "Natural gas",
  Coal_FE: "Coal",
};

interface AtbRow { m: string; f: string; c: string; y: number | string; t: string; d: string; n: string; v: (number | null)[] }
interface AtbData {
  source: string; url: string; years: number[];
  metrics: Record<string, { label: string; unit: string }>;
  techLabels: Record<string, string>; rows: AtbRow[];
}

const COLORS = ["hsl(var(--primary))", "#C65C28", "#2A7656", "#7A5C99", "#B8912F", "#3B6E8F", "#A23B54", "#5E7D2E"];
const CASES = ["Advanced", "Moderate", "Conservative"];
const MAX_LINES = 8;

export default function AtbOptions() {
  useSeo({
    title: "ATB Options | Austin Clean Energy",
    description: "Browse and filter NREL's Annual Technology Baseline costs for solar, wind, storage, gas, nuclear and more, 2022–2050.",
  });

  const [data, setData] = useState<AtbData | null>(null);
  const [error, setError] = useState(false);
  const [metric, setMetric] = useState("lcoe");
  const [costCase, setCostCase] = useState("Moderate");
  const [techs, setTechs] = useState<string[]>(["UtilityPV", "LandbasedWind", "NaturalGas_FE", "Utility-Scale Battery Storage"]);
  const [crp, setCrp] = useState("30");
  const [year, setYear] = useState(2030);
  const [q, setQ] = useState("");

  useEffect(() => {
    fetch("/data/atb.json").then((r) => r.json()).then(setData).catch(() => setError(true));
  }, []);

  const label = (t: string) => TECH_LABELS[t] ?? data?.techLabels[t] ?? t;

  const techOptions = useMemo(() => {
    if (!data) return [];
    return [...new Set(data.rows.map((r) => r.t))].map((t) => ({ value: t, label: label(t) }))
      .sort((a, b) => a.label.localeCompare(b.label));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);

  const crpOptions = useMemo(
    () => (data ? [...new Set(data.rows.filter((r) => r.m === metric).map((r) => String(r.y)))].sort() : []),
    [data, metric],
  );

  const rows = useMemo(() => {
    if (!data) return [];
    const ql = q.trim().toLowerCase();
    return data.rows.filter((r) =>
      r.m === metric &&
      (r.c === costCase || !CASES.includes(r.c)) &&
      (techs.length === 0 || techs.includes(r.t)) &&
      (String(r.y) === crp || String(r.y) === "*" || !crpOptions.includes(crp)) &&
      (!ql || `${r.n} ${label(r.t)}`.toLowerCase().includes(ql)),
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data, metric, costCase, techs, crp, q, crpOptions]);

  const missing = techs.filter((t) => !rows.some((r) => r.t === t));
  const yi = data ? data.years.indexOf(year) : -1;
  const meta = data?.metrics[metric];
  const fmt = (v: number | null) =>
    v == null ? "—" : meta?.unit === "fraction" ? `${(v * 100).toFixed(1)}%` : v.toLocaleString(undefined, { maximumFractionDigits: v < 10 ? 2 : 0 });

  const sorted = [...rows].sort((a, b) => (a.v[yi] ?? Infinity) - (b.v[yi] ?? Infinity));
  const chartRows = sorted.slice(0, MAX_LINES);
  const chartData = data?.years.map((yr, i) => {
    const o: Record<string, number | null> = { year: yr };
    chartRows.forEach((r) => (o[r.n] = r.v[i]));
    return o;
  });

  return (
    <>
      <PageHeader
        title="ATB Options"
        subtitle="Compare what NREL projects new power plants and batteries will cost, by technology, from 2022 to 2050."
        backTo="/austin-at-a-glance"
        backLabel="Back to Austin at a Glance"
      />
      <div className="max-w-6xl mx-auto px-4 py-8 space-y-6">
        <Card>
          <CardContent className="pt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            <Field label="Measure">
              <Select value={metric} onValueChange={setMetric}>
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {data && Object.entries(data.metrics).map(([k, m]) => (
                    <SelectItem key={k} value={k} className="text-xs">{m.label} ({m.unit === "fraction" ? "%" : m.unit})</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </Field>
            <Field label="Technology">
              <MultiSelectDropdown label="All technologies" options={techOptions} selected={techs} onChange={setTechs} />
            </Field>
            <Field label="Cost outlook">
              <Select value={costCase} onValueChange={setCostCase}>
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {CASES.map((c) => <SelectItem key={c} value={c} className="text-xs">{c}</SelectItem>)}
                </SelectContent>
              </Select>
            </Field>
            <Field label="Cost recovery period (years)">
              <Select value={crpOptions.includes(crp) ? crp : crpOptions[0] ?? ""} onValueChange={setCrp}>
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {crpOptions.map((c) => <SelectItem key={c} value={c} className="text-xs">{c === "*" ? "Not applicable" : c}</SelectItem>)}
                </SelectContent>
              </Select>
            </Field>
            <Field label="Year shown in table">
              <Select value={String(year)} onValueChange={(v) => setYear(Number(v))}>
                <SelectTrigger className="h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {data?.years.map((y) => <SelectItem key={y} value={String(y)} className="text-xs">{y}</SelectItem>)}
                </SelectContent>
              </Select>
            </Field>
            <Field label="Search (e.g. class 4, 4hr)">
              <Input className="h-8 text-xs" value={q} onChange={(e) => setQ(e.target.value)} placeholder="Filter by name" />
            </Field>
          </CardContent>
        </Card>

        {error && <p className="text-sm text-destructive">The ATB data could not be loaded.</p>}
        {!data && !error && <p className="text-sm text-muted-foreground">Loading…</p>}

        {data && (
          <>
            <Card>
              <CardHeader>
                <CardTitle>{meta?.label} over time</CardTitle>
                <CardDescription>
                  {costCase} outlook · {meta?.unit === "fraction" ? "share of the year at full output" : meta?.unit} ·
                  {rows.length > MAX_LINES ? ` showing the ${MAX_LINES} lowest in ${year} of ${rows.length} matches` : ` ${rows.length} matches`}
                </CardDescription>
                {missing.length > 0 && (
                  <p className="text-xs text-muted-foreground">
                    No {meta?.label.toLowerCase()} data for {missing.map(label).join(", ")} with these filters — try another measure or cost recovery period.
                  </p>
                )}
              </CardHeader>
              <CardContent>
                {chartRows.length === 0 ? (
                  <p className="text-sm text-muted-foreground">Nothing matches these filters.</p>
                ) : (
                  <div className="h-80">
                    <ResponsiveContainer width="100%" height="100%">
                      <LineChart data={chartData}>
                        <CartesianGrid strokeDasharray="3 3" className="stroke-border" />
                        <XAxis dataKey="year" tick={{ fontSize: 11 }} />
                        <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => fmt(v)} width={60} />
                        <Tooltip formatter={(v: number) => fmt(v)} />
                        <Legend wrapperStyle={{ fontSize: 11 }} />
                        {chartRows.map((r, i) => (
                          <Line key={r.n} dataKey={r.n} stroke={COLORS[i % COLORS.length]} dot={false} strokeWidth={2} connectNulls />
                        ))}
                      </LineChart>
                    </ResponsiveContainer>
                  </div>
                )}
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>All matches, cheapest first in {year}</CardTitle>
              </CardHeader>
              <CardContent className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-left text-muted-foreground border-b">
                      <th className="py-2 pr-3">Technology</th>
                      <th className="py-2 pr-3">Option</th>
                      <th className="py-2 pr-3 text-right">2024</th>
                      <th className="py-2 pr-3 text-right">{year}</th>
                      <th className="py-2 text-right">2050</th>
                    </tr>
                  </thead>
                  <tbody>
                    {sorted.map((r) => (
                      <tr key={`${r.n}-${r.c}-${r.y}`} className="border-b last:border-0">
                        <td className="py-1.5 pr-3">{label(r.t)}</td>
                        <td className="py-1.5 pr-3">{r.n}</td>
                        <td className="py-1.5 pr-3 text-right tabular-nums">{fmt(r.v[data.years.indexOf(2024)])}</td>
                        <td className="py-1.5 pr-3 text-right tabular-nums font-medium">{fmt(r.v[yi])}</td>
                        <td className="py-1.5 text-right tabular-nums">{fmt(r.v[data.years.length - 1])}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </CardContent>
            </Card>

            <p className="text-xs text-muted-foreground">
              Source: <a className="underline" href={data.url} target="_blank" rel="noreferrer">{data.source}</a>, research
              (R&amp;D) financial case, in 2022 dollars. These are national projections for new plants, not Austin Energy's actual
              costs. "Advanced," "Moderate" and "Conservative" are NREL's optimistic, middle and cautious cost outlooks. Costs
              exclude tax credits.
            </p>
          </>
        )}
      </div>
    </>
  );
}

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => (
  <div className="space-y-1.5">
    <p className="text-xs font-medium text-muted-foreground">{label}</p>
    {children}
  </div>
);
