import { useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowLeft, BoxSelect, Check, Download, FileStack, FileUp, GanttChart, Highlighter, Image as ImageIcon, MessageSquare, MousePointer2, Pencil, Ruler, Sun, Moon, Trash2, X } from "lucide-react";
import { Link } from "react-router-dom";

import { Button } from "@/components/ui/button";
import { useSharedProject } from "@/lib/shared-project";
import { cn } from "@/lib/utils";

type SheetId = "PV-0" | "PV-1" | "PV-2" | "PV-3" | "S-1" | "E-1" | "E-1.1" | "E-2" | "E-3+";
type Panel = "config" | "uploads" | "viewer" | "review";
type Tool = "pin" | "box" | "arrow" | "highlight";
type Draft = { owner: string; apn: string; ahj: string; utility: string; license: string; panelWatts: number; panelLength: number; panelWidth: number; tilt: number; inverterModel: string; inverterQty: number; roofWidth: number; roofLength: number; windSpeed: number; drafter: string };
type UploadKey = "diagram" | "modules" | "inverters" | "racking" | "transformers" | "disconnects" | "stamp" | "aerial";
type Upload = { name: string; url: string; type: string };
type Markup = { id: number; sheet: SheetId; x: number; y: number; tool: Tool; text: string; resolved: boolean };

const sheets: { id: SheetId; short: string; title: string; scale: string }[] = [
  { id: "PV-0", short: "Cover", title: "Cover Page & Code Compliance", scale: "NTS" },
  { id: "PV-1", short: "Site", title: "Site & Equipment Layout", scale: '1" = 30\'' },
  { id: "PV-2", short: "Roof", title: "Rooftop Array & Racking Layout", scale: '1/8" = 1\'' },
  { id: "PV-3", short: "BOM", title: "Bill of Materials & String Schedule", scale: "NTS" },
  { id: "S-1", short: "Structural", title: "Structural Details & Loads", scale: '3" = 1\'' },
  { id: "E-1", short: "Diagram", title: "Electrical Single-Line Diagram", scale: "NTS" },
  { id: "E-1.1", short: "Conductors", title: "Conductor & Conduit Schedule", scale: "NTS" },
  { id: "E-2", short: "Placards", title: "Placards & Safety Signage", scale: "NTS" },
  { id: "E-3+", short: "Cut Sheets", title: "Equipment Cut Sheets", scale: "NTS" },
];
const fallbackSheet = { id: "PV-0", short: "Cover", title: "Cover Page & Code Compliance", scale: "NTS" } satisfies (typeof sheets)[number];
const defaultDraft: Draft = { owner: "Property Owner", apn: "Pending", ahj: "City of Austin", utility: "Austin Energy", license: "TECL #00000", panelWatts: 550, panelLength: 2278, panelWidth: 1134, tilt: 10, inverterModel: "125 kW 480V 3Ø", inverterQty: 2, roofWidth: 180, roofLength: 260, windSpeed: 115, drafter: "ACE Design Team" };
const uploadSlots: { key: UploadKey; label: string; note: string; multiple?: boolean }[] = [
  { key: "diagram", label: "Custom 3-Line / SLD", note: "Overrides the generated E-1 sheet" },
  { key: "modules", label: "Module cut sheets", note: "PDF, PNG, or SVG", multiple: true },
  { key: "inverters", label: "Inverter cut sheets", note: "PDF, PNG, or SVG", multiple: true },
  { key: "racking", label: "Racking cut sheets", note: "PDF, PNG, or SVG", multiple: true },
  { key: "transformers", label: "Transformer cut sheets", note: "PDF, PNG, or SVG", multiple: true },
  { key: "disconnects", label: "Disconnect cut sheets", note: "PDF, PNG, or SVG", multiple: true },
  { key: "stamp", label: "PE stamp", note: "Placed in every title block" },
  { key: "aerial", label: "Site aerial image", note: "Embedded on PV-0" },
];

export function SolarDraftStudio() {
  const { project, updateProject } = useSharedProject();
  const [draft, setDraft] = useState(defaultDraft);
  const [panel, setPanel] = useState<Panel>("config");
  const [active, setActive] = useState<SheetId>("PV-0");
  const [blueprint, setBlueprint] = useState(false);
  const [uploads, setUploads] = useState<Partial<Record<UploadKey, Upload[]>>>({});
  const [markupMode, setMarkupMode] = useState(false);
  const [tool, setTool] = useState<Tool>("pin");
  const [markups, setMarkups] = useState<Markup[]>([]);
  const [pendingMarkup, setPendingMarkup] = useState<Markup | null>(null);
  const [comment, setComment] = useState("");
  const urls = useRef<string[]>([]);
  useEffect(() => () => urls.current.forEach((url) => URL.revokeObjectURL(url)), []);

  const calc = useMemo(() => {
    const modules = Math.ceil((Math.max(project.systemSizeKw, 0) * 1000) / Math.max(draft.panelWatts, 1));
    const modulesPerString = 18;
    const strings = Math.ceil(modules / modulesPerString);
    const usableWidth = Math.max(0, draft.roofWidth - 8);
    const usableLength = Math.max(0, draft.roofLength - 8);
    const moduleWidthFt = draft.panelWidth / 304.8;
    const moduleLengthFt = draft.panelLength / 304.8;
    const columns = Math.max(1, Math.floor(usableLength / (moduleWidthFt + .12)));
    const rows = Math.ceil(modules / columns);
    const arrayDepth = rows * moduleLengthFt * Math.cos((draft.tilt * Math.PI) / 180);
    const roofArea = Math.max(1, draft.roofWidth * draft.roofLength);
    const deadLoad = (modules * 62 + modules * 3.5 * 35 + modules * 8) / roofArea;
    const stringVoc = modulesPerString * 49.8 * 1.13;
    const inverterAc = draft.inverterQty * 125;
    const warnings = [...(arrayDepth > usableWidth ? ["Array exceeds the available area inside the 48 in fire setback."] : []), ...(stringVoc > 1000 ? ["Cold-weather string voltage exceeds 1,000 V DC."] : []), ...(inverterAc < project.systemSizeKw / 1.35 ? ["DC:AC ratio exceeds 1.35."] : []), ...(draft.windSpeed > 130 ? ["Enhanced perimeter ballast engineering is required."] : [])];
    return { modules, modulesPerString, strings, columns, rows, deadLoad, stringVoc, inverterAc, warnings };
  }, [draft, project.systemSizeKw]);
  const activeSheet = sheets.find((sheet) => sheet.id === active) ?? fallbackSheet;

  const update = <K extends keyof Draft>(key: K, value: Draft[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const addFiles = (key: UploadKey, list: FileList | null) => {
    if (!list) return;
    const next = Array.from(list).filter((file) => ["application/pdf", "image/png", "image/svg+xml"].includes(file.type)).map((file) => { const url = URL.createObjectURL(file); urls.current.push(url); return { name: file.name, url, type: file.type }; });
    setUploads((current) => ({ ...current, [key]: key === "modules" || key === "inverters" || key === "racking" || key === "transformers" || key === "disconnects" ? [...(current[key] ?? []), ...next] : next.slice(0, 1) }));
  };
  const addMarkup = (event: React.MouseEvent<HTMLElement>) => {
    if (!markupMode) return;
    const box = event.currentTarget.getBoundingClientRect();
    const item: Markup = { id: Date.now(), sheet: active, x: ((event.clientX - box.left) / box.width) * 100, y: ((event.clientY - box.top) / box.height) * 100, tool, text: "", resolved: false };
    setPendingMarkup(item); setComment("");
  };
  const saveMarkup = () => { if (!pendingMarkup || !comment.trim()) return; setMarkups((items) => [...items, { ...pendingMarkup, text: comment.trim() }]); setPendingMarkup(null); setComment(""); };
  const printAll = () => window.setTimeout(() => window.print(), 60);

  return <main className="min-h-screen bg-muted text-foreground">
    <header className="no-print border-b border-primary-foreground/15 bg-primary text-primary-foreground"><div className="flex flex-wrap items-center justify-between gap-3 px-4 py-3 sm:px-6"><div className="flex min-w-0 items-center gap-3"><Ruler className="size-7 shrink-0 text-accent" /><div><h1 className="font-display text-xl font-bold">SolarPlanStudio Pro</h1><p className="font-mono text-[9px] uppercase opacity-70">Austin Clean Energy · Permit review workspace</p></div></div><div className="flex gap-2"><Button asChild size="sm" variant="outline" className="border-primary-foreground/25 bg-primary text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/solar-suite/bom"><ArrowLeft /> BOM</Link></Button><Button asChild size="sm" variant="outline" className="border-primary-foreground/25 bg-primary text-primary-foreground hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/solar-suite/flow"><GanttChart /> Schedule</Link></Button></div></div></header>
    <div className="no-print grid min-h-[calc(100vh-61px)] lg:grid-cols-[230px_300px_minmax(0,1fr)]">
      <aside className="border-b border-border bg-foreground p-3 text-background lg:border-b-0 lg:border-r"><p className="px-2 pt-2 font-mono text-[10px] uppercase text-accent">Plan set tools</p><nav className="mt-3 space-y-1">{([{ id: "config", label: "Project Configuration", icon: Ruler }, { id: "uploads", label: "Upload Manager", icon: FileUp }, { id: "viewer", label: "Plan Set Viewer", icon: FileStack }, { id: "review", label: "Markup & Review", icon: MessageSquare }] as const).map((item) => <Button key={item.id} variant={panel === item.id ? "secondary" : "ghost"} onClick={() => setPanel(item.id)} className="w-full justify-start text-left text-background hover:text-foreground"><item.icon /> {item.label}</Button>)}</nav><div className="mt-6 border-t border-background/20 px-2 pt-4"><p className="font-mono text-[9px] uppercase opacity-60">Active project</p><p className="mt-1 text-sm font-semibold">{project.projectName}</p><p className="mt-1 text-xs opacity-60">{project.systemSizeKw} kW DC</p></div></aside>
      <aside className="max-h-[55vh] overflow-y-auto border-b border-border bg-background p-4 lg:max-h-[calc(100vh-61px)] lg:border-b-0 lg:border-r">
        {panel === "config" && <ConfigPanel project={project} updateProject={updateProject} draft={draft} update={update} />}
        {panel === "uploads" && <UploadPanel uploads={uploads} addFiles={addFiles} remove={(key, index) => setUploads((current) => ({ ...current, [key]: (current[key] ?? []).filter((_, i) => i !== index) }))} />}
        {panel === "viewer" && <SheetIndex active={active} setActive={setActive} />}
        {panel === "review" && <ReviewPanel markups={markups} active={active} setActive={setActive} toggle={(id) => setMarkups((items) => items.map((item) => item.id === id ? { ...item, resolved: !item.resolved } : item))} remove={(id) => setMarkups((items) => items.filter((item) => item.id !== id))} />}
      </aside>
      <section className="min-w-0 overflow-hidden"><div className="border-b border-border bg-background px-3 py-3 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-display text-sm font-bold">{activeSheet.id} · {activeSheet.title}</p><p className="font-mono text-[9px] uppercase text-muted-foreground">ARCH D · 24 × 36 in · sheet {sheets.findIndex((s) => s.id === active) + 1} of {sheets.length}</p></div><div className="flex gap-1.5"><Button size="icon" variant="outline" aria-label="Toggle blueprint" onClick={() => setBlueprint((value) => !value)}>{blueprint ? <Sun /> : <Moon />}</Button><Button variant={markupMode ? "destructive" : "outline"} onClick={() => setMarkupMode((value) => !value)}><Pencil /> <span className="hidden sm:inline">Markup</span></Button><Button onClick={printAll}><Download /> <span className="hidden sm:inline">Export package</span></Button></div></div><div className="mt-3 flex gap-1 overflow-x-auto pb-1">{sheets.map((sheet) => <Button key={sheet.id} size="sm" variant={active === sheet.id ? "default" : "outline"} onClick={() => setActive(sheet.id)} className="shrink-0">{sheet.id}</Button>)}</div>{markupMode && <div className="mt-3 flex flex-wrap items-center gap-1 border-t border-border pt-3"><span className="mr-2 font-mono text-[9px] uppercase text-destructive">Markup active</span>{([{ id: "pin", icon: MousePointer2, label: "Pin" }, { id: "box", icon: BoxSelect, label: "Box" }, { id: "arrow", icon: ArrowLeft, label: "Arrow" }, { id: "highlight", icon: Highlighter, label: "Highlight" }] as const).map((item) => <Button key={item.id} size="sm" variant={tool === item.id ? "destructive" : "outline"} onClick={() => setTool(item.id)}><item.icon /> {item.label}</Button>)}</div>}</div>
        {calc.warnings.length > 0 && <div className="border-b border-destructive/30 bg-destructive/10 px-4 py-2 text-destructive">{calc.warnings.map((warning) => <p key={warning} className="flex items-center gap-2 font-mono text-[10px] uppercase"><AlertTriangle className="size-3" /> Warning: {warning}</p>)}</div>}
        <div className="overflow-auto p-3 sm:p-6"><div className="mx-auto min-w-[720px] max-w-[1180px] shadow-xl"><CadSheet sheet={activeSheet} project={project} draft={draft} calc={calc} blueprint={blueprint} uploads={uploads} markups={markups.filter((item) => item.sheet === active)} onMarkup={addMarkup} markupMode={markupMode} /></div></div>
      </section>
    </div>
    <div className="print-plan-set hidden print-all-sheets">{sheets.map((sheet) => <CadSheet key={sheet.id} sheet={sheet} project={project} draft={draft} calc={calc} blueprint={false} uploads={uploads} markups={markups.filter((item) => item.sheet === sheet.id)} markupMode={false} />)}</div>
    {pendingMarkup && <div className="no-print fixed inset-0 z-50 grid place-items-center bg-foreground/45 p-4"><div className="w-full max-w-sm bg-background p-5 shadow-xl"><div className="flex justify-between"><h2 className="font-display text-xl font-bold">Add review note</h2><Button size="icon" variant="ghost" onClick={() => setPendingMarkup(null)}><X /></Button></div><p className="mt-1 font-mono text-[10px] uppercase text-muted-foreground">{pendingMarkup.sheet} · {pendingMarkup.tool}</p><textarea autoFocus className="mt-4 min-h-24 w-full border border-input bg-card p-3 text-sm" placeholder="Describe the required revision or @mention a reviewer" value={comment} onChange={(e) => setComment(e.target.value)} /><Button className="mt-3 w-full" onClick={saveMarkup}>Save review note</Button></div></div>}
  </main>;
}

type ProjectShape = { projectName: string; address: string; systemSizeKw: number };
function ConfigPanel({ project, updateProject, draft, update }: { project: ProjectShape; updateProject: (v: Partial<ProjectShape>) => void; draft: Draft; update: <K extends keyof Draft>(key: K, value: Draft[K]) => void }) { return <div><PanelTitle eyebrow="Shared inputs" title="Project configuration" /><Section title="Metadata"><TextInput label="Project name" value={project.projectName} onChange={(v) => updateProject({ projectName: v })} /><TextInput label="Owner" value={draft.owner} onChange={(v) => update("owner", v)} /><TextInput label="Address" value={project.address} onChange={(v) => updateProject({ address: v })} /><TextInput label="APN" value={draft.apn} onChange={(v) => update("apn", v)} /><TextInput label="AHJ" value={draft.ahj} onChange={(v) => update("ahj", v)} /><TextInput label="Utility" value={draft.utility} onChange={(v) => update("utility", v)} /></Section><Section title="Electrical specs"><NumberInput label="System capacity" suffix="kW DC" value={project.systemSizeKw} onChange={(v) => updateProject({ systemSizeKw: v })} /><NumberInput label="Panel wattage" suffix="W" value={draft.panelWatts} onChange={(v) => update("panelWatts", v)} /><TextInput label="Inverter model" value={draft.inverterModel} onChange={(v) => update("inverterModel", v)} /><NumberInput label="Inverter quantity" value={draft.inverterQty} onChange={(v) => update("inverterQty", v)} /></Section><Section title="Structural loads"><div className="grid grid-cols-2 gap-2"><NumberInput label="Roof width" suffix="ft" value={draft.roofWidth} onChange={(v) => update("roofWidth", v)} /><NumberInput label="Roof length" suffix="ft" value={draft.roofLength} onChange={(v) => update("roofLength", v)} /><NumberInput label="Tilt" suffix="°" value={draft.tilt} onChange={(v) => update("tilt", v)} /><NumberInput label="Wind speed" suffix="mph" value={draft.windSpeed} onChange={(v) => update("windSpeed", v)} /></div></Section></div>; }
function UploadPanel({ uploads, addFiles, remove }: { uploads: Partial<Record<UploadKey, Upload[]>>; addFiles: (key: UploadKey, list: FileList | null) => void; remove: (key: UploadKey, index: number) => void }) { return <div><PanelTitle eyebrow="Project documents" title="Upload manager" /><p className="mb-4 text-xs text-muted-foreground">PDF, PNG, and SVG files remain in this browser session.</p><div className="space-y-3">{uploadSlots.map((slot) => <div key={slot.key} className="border border-border p-3"><p className="text-sm font-semibold">{slot.label}</p><p className="text-[10px] text-muted-foreground">{slot.note}</p><label className="mt-2 flex cursor-pointer items-center justify-center gap-2 border border-dashed border-border bg-muted px-3 py-3 text-xs"><FileUp className="size-4 text-primary" /> Choose file{slot.multiple ? "s" : ""}<input type="file" accept=".pdf,.png,.svg,application/pdf,image/png,image/svg+xml" multiple={slot.multiple} className="sr-only" onChange={(e) => addFiles(slot.key, e.target.files)} /></label>{(uploads[slot.key] ?? []).map((file, index) => <div key={`${file.name}-${index}`} className="mt-2 flex items-center justify-between gap-2 bg-muted px-2 py-1 text-[10px]"><span className="truncate">{file.name}</span><Button size="icon" variant="ghost" className="size-7" onClick={() => remove(slot.key, index)}><Trash2 /></Button></div>)}</div>)}</div></div>; }
function SheetIndex({ active, setActive }: { active: SheetId; setActive: (id: SheetId) => void }) { return <div><PanelTitle eyebrow="Nine-sheet package" title="Plan set viewer" /><div className="space-y-2">{sheets.map((sheet, index) => <button key={sheet.id} onClick={() => setActive(sheet.id)} className={cn("w-full border p-3 text-left", active === sheet.id ? "border-primary bg-primary/5" : "border-border bg-card")}><span className="font-mono text-[9px] uppercase text-primary">{String(index + 1).padStart(2, "0")} · {sheet.id}</span><span className="mt-1 block text-xs font-semibold">{sheet.title}</span></button>)}</div></div>; }
function ReviewPanel({ markups, active, setActive, toggle, remove }: { markups: Markup[]; active: SheetId; setActive: (id: SheetId) => void; toggle: (id: number) => void; remove: (id: number) => void }) { return <div><PanelTitle eyebrow="Engineering review" title="Comments & redlines" /><div className="mb-4 grid grid-cols-2 gap-2"><div className="border border-border p-2 text-center"><strong className="block font-display text-xl">{markups.filter((m) => !m.resolved).length}</strong><span className="font-mono text-[9px] uppercase">Open</span></div><div className="border border-border p-2 text-center"><strong className="block font-display text-xl">{markups.filter((m) => m.resolved).length}</strong><span className="font-mono text-[9px] uppercase">Resolved</span></div></div>{markups.length === 0 ? <p className="border border-dashed border-border p-5 text-center text-xs text-muted-foreground">Turn on Markup, select a tool, and click a drawing to add a review note.</p> : <div className="space-y-2">{markups.map((item) => <article key={item.id} className={cn("border p-3", item.resolved ? "border-border opacity-60" : "border-destructive/40 bg-destructive/5")}><button className="w-full text-left" onClick={() => setActive(item.sheet)}><p className="font-mono text-[9px] uppercase text-destructive">{item.sheet} · {item.tool}</p><p className="mt-1 text-xs">{item.text}</p></button><div className="mt-2 flex gap-1"><Button size="sm" variant="outline" onClick={() => toggle(item.id)}><Check /> {item.resolved ? "Reopen" : "Resolve"}</Button><Button size="icon" variant="ghost" onClick={() => remove(item.id)}><Trash2 /></Button></div></article>)}</div>}<p className="mt-4 text-[10px] text-muted-foreground">Showing {markups.filter((item) => item.sheet === active).length} notes on {active}.</p></div>; }
function PanelTitle({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mb-5"><p className="font-mono text-[9px] uppercase text-primary">{eyebrow}</p><h2 className="font-display text-xl font-bold">{title}</h2></div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mb-5 border-t border-border pt-3"><h3 className="mb-3 font-mono text-[10px] font-semibold uppercase text-primary">{title}</h3><div className="space-y-2">{children}</div></section>; }
function TextInput({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) { return <label className="block"><span className="font-mono text-[9px] uppercase text-muted-foreground">{label}</span><input className="mt-1 w-full rounded-sm border border-input bg-card px-2.5 py-2 text-xs outline-none focus:border-primary" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function NumberInput({ label, suffix, value, onChange }: { label: string; suffix?: string; value: number; onChange: (v: number) => void }) { return <label className="block"><span className="font-mono text-[9px] uppercase text-muted-foreground">{label}</span><span className="mt-1 flex items-center rounded-sm border border-input bg-card px-2.5"><input type="number" min="0" className="min-w-0 w-full bg-transparent py-2 font-mono text-xs outline-none" value={value} onChange={(e) => onChange(Math.max(0, Number(e.target.value)))} />{suffix && <span className="text-[9px] text-muted-foreground">{suffix}</span>}</span></label>; }

type Calc = { modules: number; modulesPerString: number; strings: number; columns: number; rows: number; deadLoad: number; stringVoc: number; inverterAc: number; warnings: string[] };
function CadSheet({ sheet, project, draft, calc, blueprint, uploads, markups, onMarkup, markupMode }: { sheet: (typeof sheets)[number]; project: ProjectShape; draft: Draft; calc: Calc; blueprint: boolean; uploads: Partial<Record<UploadKey, Upload[]>>; markups: Markup[]; onMarkup?: (e: React.MouseEvent<HTMLElement>) => void; markupMode: boolean }) { return <article onClick={onMarkup} className={cn("cad-sheet relative aspect-[3/2] overflow-hidden border", markupMode && "cursor-crosshair", blueprint ? "border-primary-foreground/30 bg-primary text-primary-foreground" : "border-foreground/30 bg-card text-foreground")}><div className="grid h-full grid-cols-[minmax(0,1fr)_17%]"><div className="relative min-w-0 overflow-hidden p-[2.2%]"><div className="flex items-end justify-between border-b-2 border-current pb-[1%]"><div><p className="font-mono text-[1.1cqw] font-bold uppercase">Austin Clean Energy</p><h2 className="font-mono text-[1.8cqw] font-bold uppercase">{sheet.title}</h2></div><p className="font-mono text-[0.8cqw]">ISSUED FOR PERMIT</p></div><Drawing id={sheet.id} project={project} draft={draft} calc={calc} uploads={uploads} /></div><TitleBlock sheet={sheet} project={project} draft={draft} calc={calc} stamp={uploads.stamp?.[0]} /></div>{markups.map((item, index) => <MarkupShape key={item.id} item={item} number={index + 1} />)}</article>; }
function TitleBlock({ sheet, project, draft, calc, stamp }: { sheet: (typeof sheets)[number]; project: ProjectShape; draft: Draft; calc: Calc; stamp: Upload | undefined }) { return <aside className="flex min-w-0 flex-col border-l-2 border-current font-mono text-[0.7cqw] uppercase"><div className="grid flex-1 place-items-center overflow-hidden border-b border-current p-[8%] text-center">{stamp && stamp.type !== "application/pdf" ? <img src={stamp.url} alt="PE stamp" className="max-h-full max-w-full object-contain" /> : <div className="grid aspect-square w-[74%] place-items-center rounded-full border-2 border-dashed border-current">PE STAMP<br />{stamp ? "ATTACHED" : "PLACEHOLDER"}</div>}</div><div className="border-b border-current p-[7%]"><p className="text-[1.1cqw] font-bold">{project.projectName || "Untitled Project"}</p><p className="mt-[4%] normal-case">{project.address}</p></div><TitleRow label="Owner" value={draft.owner} /><TitleRow label="APN" value={draft.apn} /><TitleRow label="AHJ / Utility" value={`${draft.ahj} / ${draft.utility}`} /><TitleRow label="System" value={`${project.systemSizeKw} kW DC`} /><TitleRow label="Date" value={new Intl.DateTimeFormat("en-US").format(new Date())} /><TitleRow label="Scale" value={sheet.scale} /><div className="p-[7%]"><p className="text-[2.3cqw] font-bold">{sheet.id}</p><p>SHEET {sheets.findIndex((s) => s.id === sheet.id) + 1} OF {sheets.length}</p><p>{calc.modules} MODULES</p></div></aside>; }
function TitleRow({ label, value }: { label: string; value: string }) { return <div className="border-b border-current p-[5%]"><span className="opacity-60">{label}</span><p className="truncate font-bold normal-case">{value}</p></div>; }
function MarkupShape({ item, number }: { item: Markup; number: number }) { const common = { left: `${item.x}%`, top: `${item.y}%` }; if (item.tool === "pin") return <span className="absolute z-20 grid size-6 -translate-x-1/2 -translate-y-full place-items-center rounded-full bg-destructive text-[10px] font-bold text-destructive-foreground" style={common}>{number}</span>; if (item.tool === "arrow") return <span className="absolute z-20 h-0.5 w-16 origin-left rotate-[-25deg] bg-destructive after:absolute after:-right-1 after:-top-1 after:size-2 after:rotate-45 after:border-r-2 after:border-t-2 after:border-destructive" style={common} />; return <span className={cn("absolute z-20 h-[12%] w-[18%] -translate-x-1/2 -translate-y-1/2 border-2", item.tool === "highlight" ? "border-accent bg-accent/30" : "border-destructive")} style={common} />; }

function Drawing({ id, project, draft, calc, uploads }: { id: SheetId; project: ProjectShape; draft: Draft; calc: Calc; uploads: Partial<Record<UploadKey, Upload[]>> }) {
  if (id === "PV-0") return <Cover project={project} draft={draft} calc={calc} aerial={uploads.aerial?.[0]} />;
  if (id === "PV-1") return <Site draft={draft} calc={calc} />;
  if (id === "PV-2") return <Roof draft={draft} calc={calc} />;
  if (id === "PV-3") return <Bom draft={draft} calc={calc} />;
  if (id === "S-1") return <Structural draft={draft} calc={calc} />;
  if (id === "E-1") return <Electrical draft={draft} calc={calc} custom={uploads.diagram?.[0]} />;
  if (id === "E-1.1") return <Conductors calc={calc} />;
  if (id === "E-2") return <Safety />;
  return <CutSheets uploads={uploads} />;
}
function Cover({ project, draft, calc, aerial }: { project: ProjectShape; draft: Draft; calc: Calc; aerial: Upload | undefined }) { const summary = [["DC system", `${project.systemSizeKw} kW`], ["PV modules", String(calc.modules)], ["Inverter AC", `${calc.inverterAc} kW`], ["Strings", String(calc.strings)]]; return <div className="grid h-[86%] grid-cols-[1.05fr_.95fr] gap-[3%] pt-[3%] font-mono text-[.75cqw]"><div><Heading>PROJECT SUMMARY</Heading><div className="mt-[2%] border border-current">{summary.map(([a,b]) => <div key={a} className="grid grid-cols-2 border-b border-current last:border-0"><span className="p-[2%]">{a}</span><strong className="border-l border-current p-[2%]">{b}</strong></div>)}</div><Heading extra="mt-[5%]">GOVERNING CODES</Heading><p className="mt-[2%] leading-[1.8]">NFPA 70 — NEC 2023 / 2026<br />IBC 2021 · IFC 2021<br />CITY OF AUSTIN SOLAR REQUIREMENTS<br />AUSTIN ENERGY INTERCONNECTION MANUAL</p><Heading extra="mt-[5%]">SHEET INDEX</Heading>{sheets.map((s) => <div key={s.id} className="flex justify-between border-b border-current/30 py-[.7%]"><strong>{s.id}</strong><span>{s.title}</span></div>)}</div><div><Heading>SITE LOCATION</Heading><div className="relative mt-[2%] aspect-[4/3] overflow-hidden border border-current">{aerial && aerial.type !== "application/pdf" ? <img src={aerial.url} alt="Site aerial" className="h-full w-full object-cover" /> : <MapGraphic />}<span className="absolute bottom-[4%] left-[4%] max-w-[85%] border border-current bg-card px-[3%] py-[2%] text-foreground">{aerial ? "UPLOADED SITE AERIAL" : "SATELLITE / GIS PLACEHOLDER"}<br />{project.address}</span></div><p className="mt-[3%]">OWNER: {draft.owner}<br />APN: {draft.apn}<br />AHJ: {draft.ahj}<br />UTILITY: {draft.utility}</p></div></div>; }
function MapGraphic() { return <svg viewBox="0 0 400 300" className="h-full w-full opacity-70"><path d="M0 45H400M0 110H400M0 245H400M65 0V300M180 0V300M330 0V300M0 190L400 70" fill="none" stroke="currentColor" strokeWidth="2"/><rect x="145" y="102" width="115" height="82" fill="currentColor" opacity=".12" stroke="currentColor" strokeWidth="3"/></svg>; }
function Site({ draft, calc }: { draft: Draft; calc: Calc }) { return <div className="grid h-[86%] grid-cols-[1fr_.3fr] gap-[3%] pt-[3%] font-mono text-[.75cqw]"><svg viewBox="0 0 700 430" className="h-full w-full border border-current"><path d="M35 45H660V390H35Z" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M75 85H540V345H75Z" fill="none" stroke="currentColor" strokeWidth="4"/><path d="M110 120H500V305H110Z" fill="currentColor" opacity=".08" stroke="currentColor" strokeWidth="2"/><circle cx="585" cy="205" r="18" fill="none" stroke="currentColor" strokeWidth="2"/><text x="285" y="210" fill="currentColor" textAnchor="middle" fontSize="15">ROOFTOP PV ARRAY · {calc.modules} MODULES</text><text x="548" y="78" fill="currentColor" fontSize="11">UTILITY SERVICE</text></svg><div><Heading>SITE NOTES</Heading><p className="mt-[4%] leading-[1.8]">1. VERIFY ALL SITE DIMENSIONS.<br />2. MAINTAIN FIRE ACCESS.<br />3. COORDINATE UTILITY POI.<br />4. ROOF: {draft.roofWidth} × {draft.roofLength} FT.</p></div></div>; }
function Roof({ draft, calc }: { draft: Draft; calc: Calc }) { const shown = Math.min(calc.modules, 180); const cols = Math.min(calc.columns, 24); const rows = Math.ceil(shown / cols); return <div className="h-[86%] pt-[3%] font-mono text-[.75cqw]"><svg viewBox="0 0 820 430" className="h-full w-full border border-current"><rect x="18" y="18" width="784" height="394" fill="none" stroke="currentColor" strokeWidth="3"/><rect x="42" y="42" width="736" height="346" fill="none" stroke="currentColor" strokeWidth="2" strokeDasharray="8 6"/><text x="52" y="60" fill="currentColor" fontSize="11">48 IN IFC FIRE ACCESS SETBACK</text>{Array.from({ length: shown }, (_, i) => { const col = i % cols; const row = Math.floor(i / cols); const w = Math.min(21, 610 / cols); const h = Math.min(32, 275 / Math.max(rows,1)); return <rect key={i} x={72 + col*(w+2)} y={78 + row*(h+2)} width={w} height={h} fill="currentColor" fillOpacity={(i%4)*.045+.06} stroke="currentColor"/>; })}<rect x="705" y="115" width="45" height="70" fill="none" stroke="currentColor" strokeWidth="2"/><text x="727" y="105" fill="currentColor" textAnchor="middle" fontSize="9">INV PAD</text><text x="410" y="405" fill="currentColor" textAnchor="middle" fontSize="10">RACKING COORDINATES · {draft.tilt} DEG TILT · {calc.columns} COLUMNS × {calc.rows} ROWS</text></svg></div>; }
function Bom({ draft, calc }: { draft: Draft; calc: Calc }) { const rows = [["PV MODULE", `${draft.panelWatts} W`, calc.modules, "EA"], ["STRING INVERTER", draft.inverterModel, draft.inverterQty, "EA"], ["BALLAST TRAY", "10 DEG COMMERCIAL", Math.ceil(calc.modules*1.12), "EA"], ["CONCRETE PAVER", "35 LB", Math.ceil(calc.modules*3.5), "EA"], ["PV WIRE", "#10 AWG CU", calc.modules*12, "FT"], ["MODULE STRINGS", `${calc.modulesPerString} MOD / STRING`, calc.strings, "EA"]]; return <div className="h-[86%] pt-[3%] font-mono text-[.75cqw]"><Heading>DYNAMIC BILL OF MATERIALS</Heading><div className="mt-[2%] border border-current"><div className="grid grid-cols-[1fr_1.4fr_.4fr_.3fr] bg-current/10 font-bold"><span className="p-[2%]">ITEM</span><span className="p-[2%]">DESCRIPTION</span><span className="p-[2%]">QTY</span><span className="p-[2%]">UNIT</span></div>{rows.map((row) => <div key={String(row[0])} className="grid grid-cols-[1fr_1.4fr_.4fr_.3fr] border-t border-current"><span className="p-[2%] font-bold">{row[0]}</span><span className="p-[2%]">{row[1]}</span><span className="p-[2%]">{row[2]}</span><span className="p-[2%]">{row[3]}</span></div>)}</div><Heading extra="mt-[5%]">STRING SCHEDULE</Heading><p className="mt-[2%]">{calc.strings} STRINGS · {calc.modulesPerString} MODULES IN SERIES · {calc.stringVoc.toFixed(0)} VDC COLD VOC</p></div>; }
function Structural({ draft, calc }: { draft: Draft; calc: Calc }) { return <div className="grid h-[86%] grid-cols-[1fr_.4fr] gap-[3%] pt-[3%] font-mono text-[.75cqw]"><div><Heading>TYPICAL BALLASTED RACK CROSS SECTION</Heading><svg viewBox="0 0 620 300" className="mt-[2%] w-full border border-current"><path d="M35 245H585" stroke="currentColor" strokeWidth="5"/><path d="M130 205L470 145" stroke="currentColor" strokeWidth="8"/><path d="M155 201v44M445 150v95" stroke="currentColor" strokeWidth="4"/><rect x="120" y="218" width="80" height="27" fill="none" stroke="currentColor" strokeWidth="3"/><rect x="410" y="218" width="80" height="27" fill="none" stroke="currentColor" strokeWidth="3"/><text x="150" y="173" fill="currentColor" fontSize="12">{draft.tilt}°</text><text x="305" y="278" fill="currentColor" textAnchor="middle" fontSize="11">ROOF MEMBRANE / COVER BOARD / DECK</text></svg></div><div><div className="border-2 border-current p-[7%]"><p>CALCULATED DEAD LOAD</p><strong className="mt-[4%] block text-[2.4cqw]">{calc.deadLoad.toFixed(1)}</strong><span>LB / FT²</span></div><div className="mt-[8%] border border-current p-[6%]"><strong>DESIGN CRITERIA</strong><p className="mt-[5%] leading-[1.7]">WIND: {draft.windSpeed} MPH<br />EXPOSURE: C<br />FIELD: 3 BLOCKS / MOD<br />EDGE: 4 BLOCKS / MOD<br />CORNER: 5 BLOCKS / MOD</p></div></div></div>; }
function Electrical({ draft, calc, custom }: { draft: Draft; calc: Calc; custom: Upload | undefined }) { if (custom) return <div className="grid h-[86%] place-items-center pt-[3%] font-mono text-[.75cqw]">{custom.type === "application/pdf" ? <object data={custom.url} type="application/pdf" className="h-full w-full border border-current"><p>{custom.name}</p></object> : <img src={custom.url} alt="Custom electrical diagram" className="max-h-full max-w-full object-contain" />}<span className="absolute bottom-[3%] left-[3%] border border-current bg-card px-[2%] py-[1%] text-foreground">CUSTOM DIAGRAM · {custom.name}</span></div>; const nodes = [[80,"PV STRINGS"],[240,"DC DISCONNECT"],[400,"STRING INVERTER"],[560,"AC DISCONNECT"],[720,"UTILITY TAP"]] as const; return <div className="h-[86%] pt-[3%] font-mono text-[.75cqw]"><svg viewBox="0 0 820 390" className="h-full w-full border border-current"><path d="M135 150H185M295 150H345M455 150H505M615 150H665" stroke="currentColor" strokeWidth="4"/>{nodes.map(([x,title]) => <g key={title}><rect x={x-55} y="112" width="110" height="76" fill="none" stroke="currentColor" strokeWidth="2"/><text x={x} y="145" fill="currentColor" textAnchor="middle" fontSize="10" fontWeight="bold">{title}</text></g>)}<text x="410" y="255" fill="currentColor" textAnchor="middle" fontSize="12">{calc.strings} STRINGS · {draft.inverterModel} · 480V 3Ø</text></svg></div>; }
function Conductors({ calc }: { calc: Calc }) { const rows = [["PV SOURCE", "#10 AWG PV WIRE", '3/4" EMT', "23%", "1.2%"], ["INVERTER OUTPUT", "#3/0 AWG CU THHN", '2" EMT', "31%", "1.7%"], ["GROUNDING", "#6 AWG BARE CU", "OPEN / EMT", "—", "—"]]; return <div className="h-[86%] pt-[3%] font-mono text-[.75cqw]"><Heading>CONDUCTOR, CONDUIT & VOLTAGE DROP SCHEDULE</Heading><div className="mt-[2%] border border-current">{rows.map((row) => <div key={row[0]} className="grid grid-cols-[1fr_1.4fr_.8fr_.5fr_.5fr] border-b border-current p-[2%] last:border-0">{row.map((cell, index) => <span key={`${cell}-${index}`}>{cell}</span>)}</div>)}</div><div className="mt-[5%] grid grid-cols-3 gap-[2%]"><Callout title="MAX STRING VOC" value={`${calc.stringVoc.toFixed(0)} VDC`} /><Callout title="MODULES / STRING" value={String(calc.modulesPerString)} /><Callout title="STRING COUNT" value={String(calc.strings)} /></div></div>; }
function Safety() { const labels = ["WARNING — PHOTOVOLTAIC POWER SOURCE", "RAPID SHUTDOWN SWITCH FOR SOLAR PV SYSTEM", "CAUTION — DUAL POWER SOURCE", "PV SYSTEM AC DISCONNECT", "ELECTRIC SHOCK HAZARD — TERMINALS MAY BE ENERGIZED"]; return <div className="grid h-[86%] grid-cols-2 gap-[3%] pt-[3%] font-mono text-[.75cqw]"><div>{labels.map((label, i) => <div key={label} className={cn("mb-[3%] border-2 border-current p-[3%] text-center font-bold", i === 1 && "border-destructive text-destructive")}>{label}</div>)}</div><svg viewBox="0 0 390 300" className="w-full border border-current"><rect x="45" y="35" width="300" height="220" fill="none" stroke="currentColor" strokeWidth="3"/><rect x="90" y="75" width="120" height="90" fill="currentColor" opacity=".1" stroke="currentColor" strokeWidth="2"/><circle cx="270" cy="205" r="18" fill="none" stroke="currentColor" strokeWidth="3"/><text x="150" y="120" fill="currentColor" textAnchor="middle" fontSize="12">PV ARRAY</text><text x="270" y="238" fill="currentColor" textAnchor="middle" fontSize="9">RAPID SHUTDOWN</text></svg></div>; }
function CutSheets({ uploads }: { uploads: Partial<Record<UploadKey, Upload[]>> }) { const files = (["modules","inverters","racking","transformers","disconnects"] as UploadKey[]).flatMap((key) => (uploads[key] ?? []).map((file) => ({ key, file }))); return <div className="h-[86%] pt-[3%] font-mono text-[.75cqw]"><Heading>EQUIPMENT SUBMITTAL INDEX</Heading>{files.length === 0 ? <div className="mt-[4%] grid h-[70%] place-items-center border border-dashed border-current text-center"><div><ImageIcon className="mx-auto mb-2 size-8" /><strong>NO CUT SHEETS ATTACHED</strong><p className="mt-2 opacity-60">ADD MODULE, INVERTER, RACKING, TRANSFORMER,<br />OR DISCONNECT DOCUMENTS IN UPLOAD MANAGER</p></div></div> : <div className="mt-[3%] grid grid-cols-2 gap-[2%]">{files.map(({key,file}, i) => <div key={`${key}-${file.name}-${i}`} className="flex items-center gap-[3%] border border-current p-[3%]"><FileStack className="size-[2cqw]" /><div><strong>{String(key).toUpperCase()}</strong><p>{file.name}</p></div></div>)}</div>}</div>; }
function Heading({ children, extra }: { children: React.ReactNode; extra?: string }) { return <h3 className={cn("border-b border-current pb-[1%] text-[1.05cqw] font-bold", extra)}>{children}</h3>; }
function Callout({ title, value }: { title: string; value: string }) { return <div className="border-2 border-current p-[5%]"><p>{title}</p><strong className="mt-[3%] block text-[1.8cqw]">{value}</strong></div>; }
